# Site Settings
title: Método de solfeo LAZ
email: profesor.asix@gmail.com
description: >
  Metodo de solfeo LAZ
baseurl: ""
url: "http://sorolla-jekyll.herokuapp.com"
#twitter_username: taniarascia
github_username:  profesorasix
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/pdf"
    values:
      pdf: true
  - scope:
      path: "assets/midi"
    values:
      midi: true
